services:
  tg-service:
    build:
      context: .
      dockerfile: apps/tg-service/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - .env
    volumes:
      - .env:/root/.env
    depends_on:
      - gpt-service
  gpt-service:
    build:
      context: .
      dockerfile: apps/gpt-service/Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - .env
    volumes:
      - .env:/root/.env
  gateway-service:
    build:
      context: .
      dockerfile: apps/gateway-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - gpt-service
